import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";
import { InferGetServerSidePropsType } from "next";
import React from "react";

const arr = [728540, 209080, 931690, 654310, 346110, 407530];

export default function Home({
  games,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.flexRow}>
          {games
            .filter((r: Game) => !arr.includes(r.appid))
            .map((game: Game) => {
              return (
                <div key={game.appid} className={styles.treeDimensionCard}>
                  <Image
                    src={`https://steamcdn-a.akamaihd.net/steam/apps/${game.appid}/library_600x900_2x.jpg`}
                    alt="game"
                    fill
                    loading="lazy"
                  />
                </div>
              );
            })}
        </div>
      </main>
    </>
  );
}

interface Game {
  [x: string]: any;
  appid: number;
  rtime_last_played: number;
}

export const getServerSideProps: GetServerSideProps<{
  games: Game;
}> = async () => {
  const res = await fetch(
    `https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=${process.env.STEAM_WEB_API_KEY}&steamid=${process.env.STEAM_ID}&include_appinfo=true&format=json/`
  );
  const data = await res.json();

  return {
    props: {
      games: data.response.games,
    },
  };
};
